// <auto-generated />
using System;
using EFCore7ProvidersTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore7ProvidersTest.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230214081216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("EFCore7ProvidersTest.DAL.StudyPeriod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("StudyYearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudyYearId");

                    b.ToTable("StudyPeriods");
                });

            modelBuilder.Entity("EFCore7ProvidersTest.DAL.StudyYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StudyYears", (string)null);

                    b.SplitToTable("StudyYears", "test_text", t =>
                        {
                            t.Property("Description");
                        });
                });

            modelBuilder.Entity("EFCore7ProvidersTest.DAL.StudyPeriod", b =>
                {
                    b.HasOne("EFCore7ProvidersTest.DAL.StudyYear", "StudyYear")
                        .WithMany("StudyPeriods")
                        .HasForeignKey("StudyYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyYear");
                });

            modelBuilder.Entity("EFCore7ProvidersTest.DAL.StudyYear", b =>
                {
                    b.HasOne("EFCore7ProvidersTest.DAL.StudyYear", null)
                        .WithOne()
                        .HasForeignKey("EFCore7ProvidersTest.DAL.StudyYear", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore7ProvidersTest.DAL.StudyYear", b =>
                {
                    b.Navigation("StudyPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
